remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "sunrise"

title: Deepak's Blog
name: "Deepak Chauahan"
url: "https://midstein.github.io/"
repository: "midstein/MidStein.github.io"
enable_copy_code_button: true

author:
  name: "Deepak Chauhan"
  avatar: "/assets/photo/bio-photo.jpg"
  bio: "Java Programmer, CLI Enthusiast"
  location: "Mumbai"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:deepakchauhan19feb@gmail.com"
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MidStein"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/deepak-chauhan-dev/"

include: ["_pages"]

plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
